#!/usr/bin/python3

import os, sys
sys.path = [".", ".."] + [os.path.dirname(os.path.abspath(sys.argv[0]))] + sys.path

import subprocess

from SpecBot import SpecBot
from tstcommon import *
from Date import Date
from Transaction import Transaction
import Config
import tstcommon
from tstcommon import TstCommon
from WgetTst import WgetTst

pf = Config.PASSWORD_FILE_SMTP 
if pf[0] != '/':
	Config.PASSWORD_FILE_SMTP = "../" + pf


def doTest():
	sb = SpecBot(
		dbFile = tstcommon.TST_DB_FILE,
		dbName = tstcommon.TST_DB_NAME,
		currency1str = "USD",
		currency2str = "RUB",
		readOnly = False,
		tmpDir = tstcommon.TST_TMP_DIR,
		wget = WgetTst(),
	)
	sb.updateMarketState()

	am = 10000
	r1 = 60
	r2 = 59
	t = Transaction(sb,
		amount = am,
		rate1 = r1,
		rate2 = 1/r2,
		curPair = sb.curPair,
		wm_tid1 = 15,
		wm_tid2 = 16,
	)
	t.remainder2 = t.remainder1 * r1

	i = 0
	for f in [
		sb._emailOpen1,
		sb._emailOpen2,
		sb._emailClosed1,
		sb._emailClosed2,
	]:
		if i > 1: print("")
		(subj, body) = f(t, send=False, stdout=True)
		i += 1


for mssrc in [Config.MSSRC_XML, Config.MSSRC_HTML]:
	Config.MARKETSTATE_SOURCE = mssrc
	with TstCommon():
		doTest()
