#!/usr/bin/python3

import os, sys
sys.path = [".", ".."] + [os.path.dirname(os.path.abspath(sys.argv[0]))] + sys.path

from SpecBot import SpecBot
from Transaction import Transaction
import Config
import tstcommon
from tstcommon import TstCommon
from WgetTst import WgetTst
from Bid import Bid
from defs import *
import defs
from Date import Date

# Model the situation that happened on 2017-09-25 in the morning

Config.MIN_REL_PROFIT = 0.0010
Config.RATE_SETTING_MODE = Config.RSM_MIN_PROFIT

mrp = Config.MIN_REL_PROFIT

with TstCommon():
	sb = SpecBot(
		dbFile = tstcommon.TST_DB_FILE,
		dbName = tstcommon.TST_DB_NAME,
		currency1str = "USD",
		currency2str = "RUB",
		readOnly = False,
		tmpDir = tstcommon.TST_TMP_DIR,
		wget = WgetTst(),
	)

	cp = sb.curPair
	cpr = sb.curPair.reverse()

	from MarketState import MarketState
	ms = MarketState(sb, date = Date("now"))
	ms.bids = [
		Bid(sb,
			amount1 = 1,
			amount2 = 59.7959,
			curPair = cp,
			place = 1,
			marketState = ms,
		),
		Bid(sb,
			amount1 = 59.0412,
			amount2 = 1,
			curPair = cpr,
			place = 1,
			marketState = ms,
		),
	]
	ms.save()
	sb.marketState = ms

	sb.timeAvgRates(recalculate=True)

	#ms.avgRates[cp] = 59.7959
	#ms.avgRates[cpr] = 1 / 59.0412

	r1 = 59.52501319796954
	r2 = 0

	t = Transaction(sb,
		#status = TRST_OPEN2,
		status = TRST_CLOSED1,
		amount = 9900,
		curPair = cp,
		rate1 = r1,
		rate2 = r2,
	)
	t.remainder1 = 0
	#t.remainder2 = 584821.38
	t.remainder2 = 586321.38

	sb.setRate2(t)
	t.status = TRST_OPEN2
	t.remainder2 -= t.getCommission2()

	rp = t.profit(relative = True)
	if abs(rp - mrp) > 1e-8:
		raise Exception("incorrectly set rate2")
	if abs(t.remainder2 * t.rate2 - (1 + mrp) * t.amount) > 1e-6:
		raise Exception("incorrectly set rate2=%.6f; rp=%.6f" % (1/t.rate2, rp))
